<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-04T08:13:43 WIB" name="Default suite" finished-at="2024-04-04T08:15:42 WIB" duration-ms="119630">
    <groups>
    </groups>
    <test started-at="2024-04-04T08:13:43 WIB" name="Default test" finished-at="2024-04-04T08:15:42 WIB" duration-ms="119630">
      <class name="laurachen.appium.LoginTest">
        <test-method is-config="true" signature="configureAppium()[pri:0, instance:laurachen.appium.LoginTest@1b11171f]" started-at="2024-04-04T08:13:43 WIB" name="configureAppium" finished-at="2024-04-04T08:14:03 WIB" duration-ms="19950" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configureAppium -->
        <test-method signature="loginWithInvalidCredential()[pri:0, instance:laurachen.appium.LoginTest@1b11171f]" started-at="2024-04-04T08:14:03 WIB" name="loginWithInvalidCredential" finished-at="2024-04-04T08:14:51 WIB" duration-ms="48801" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect account or password. 5 attempts remaining. Try again.] but found [Username or password doesn't match our records. Try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect account or password. 5 attempts remaining. Try again.] but found [Username or password doesn't match our records. Try again.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at laurachen.appium.LoginTest.loginWithInvalidCredential(LoginTest.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidCredential -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:laurachen.appium.LoginTest@1b11171f]" started-at="2024-04-04T08:14:51 WIB" name="tearDown" finished-at="2024-04-04T08:14:53 WIB" duration-ms="1992" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="configureAppium()[pri:0, instance:laurachen.appium.LoginTest@1b11171f]" started-at="2024-04-04T08:14:53 WIB" name="configureAppium" finished-at="2024-04-04T08:15:13 WIB" duration-ms="19266" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configureAppium -->
        <test-method signature="loginWithValidCredential()[pri:0, instance:laurachen.appium.LoginTest@1b11171f]" started-at="2024-04-04T08:15:13 WIB" name="loginWithValidCredential" finished-at="2024-04-04T08:15:41 WIB" duration-ms="28131" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredential -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:laurachen.appium.LoginTest@1b11171f]" started-at="2024-04-04T08:15:41 WIB" name="tearDown" finished-at="2024-04-04T08:15:42 WIB" duration-ms="1431" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- laurachen.appium.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
